rm(list = ls()); cat("\014"); graphics.off()

library(dplyr)
library(ggplot2)

nrep <- 1:50
nv <- seq(100, 400, 100)
nov <- seq(1, 20, 2)
cutoff <- 5

cnames <- c("i", "n", "no", "nonew", "h", "int_b", "typeI")
dd <- data.frame(matrix(NA, ncol = length(cnames)))
names(dd) <- cnames

ii <- 1
for (n in nv) {
  for (no in nov) {
    for (i in nrep) {
      set.seed((n * 100) + (no * 10) + i)
      tryCatch({
        X1 <- rnorm(n)
        X2 <- factor(sample(c(0, 1), n, replace = T), levels = c(0, 1))
        Y <- .5 * X1 + .5 * as.numeric(X2) + rnorm(n)
        d <- data.frame(X1, X2, Y)
        
        ids <- which(d$X2 == "1")
        ns <- round(no * length(ids) / 100)
        ids <- sample(ids, ns)
        d[ids, "X1"] <- d[ids, "X1"] + cutoff * sd(d$X1)
        nonew <- round(length(ids) / nrow(d) * 100)
        
        f <- lm(Y ~ X1 * X2, d)
        s <- summary(f)
        int_b <- s$coefficients["X1:X21", 1]
        int_p <- s$coefficients["X1:X21", 4]
        typeI <- as.numeric(int_p < 0.05)
        h <- mean(hatvalues(f)[ids])
        
        dd[ii, ] <- c(i, n, no, nonew, h, int_b, typeI)
      }, error = function(e) {
        dd[ii, ] <<- c(i, n, no, nonew, rep(NA, 3))
      })
      ii <- ii + 1
    }    
  }
}

ddd <- dd %>%
  group_by(n, nonew) %>%
  select(-i) %>%
  summarise(across(everything(), ~mean(.x, na.rm = T)), .groups = "drop") %>%
  as.data.frame()

p1 <- ggplot(ddd, aes(x = nonew, y = typeI, color = factor(n), group = factor(n))) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  geom_hline(yintercept = 0.05, color = "black", linetype = "dashed") +
  scale_x_continuous(breaks = unique(ddd$nonew)) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2)) +
  labs(title = "Spurious Interactions: Type I Error Rate",
       subtitle = "Percentage of false positives generated by asymmetric outliers",
       x = "Percentage of Outliers",
       y = "Type I Error Rate (p < .05)",
       color = "Sample Size (n)") +
  theme_bw()
print(p1)

p2 <- ggplot(ddd, aes(x = nonew, y = h, color = factor(n), group = factor(n))) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  scale_x_continuous(breaks = unique(ddd$nonew)) +
  labs(title = "Leverage (h) Dynamics",
       subtitle = "Mean leverage value of the injected outliers",
       x = "Percentage of Outliers",
       y = "Mean Leverage (h)",
       color = "Sample Size (n)") +
  theme_bw()
print(p2)